### ISSUE TITLE
website for example documentation is not avaible.

### ISSUE THREAD

**Issue by BigGiAnts** [KennethEnevoldsen/snp-transformer#42]
Thank you! This is a very interesting project. I want to run snp-transformer, but I have limited knowledge about coding, and don't know how to use it. Could you please fix the issue at your convenience?
Web site: https://kennethenevoldsen.github.io/snp-transformer/

**Comment by KennethEnevoldsen** [comment]
Hi @BigGiAnts thanks for your interest in this project. The project is still under active development and I am not maintaining an active website.

**Comment by BigGiAnts** [comment]
Thank you @KennethEnevoldsen
